# Generated by Django 5.0.6 on 2026-09-11 14:06

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'Le pseudo est obligatoire.', 'unique': 'Ce pseudo est déjà pris.'}, max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Le pseudo doit contenir au moins 3 caractères.'), users.validators.PermissiveUsernameValidator(), users.validators.ReservedUsernameValidator()], verbose_name='Pseudo'),
        ),
    ]
