# Generated by Django 5.0.6 on 2026-09-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Progression %'),
        ),
        migrations.AddField(
            model_name='work',
            name='last_update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière mise à jour'),
        ),
    ]
