# Generated by Django 5.0.6 on 2026-09-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_readingprogress_progress_percent_work_last_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='scroll_position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position de scroll (px)'),
        ),
    ]
